### ISSUE TITLE
Error in eval3d.py

### ISSUE THREAD

**Issue by RamyaRaghuraman** [ashafaei/OD-test#2]
Hi @ashafaei ,

Really impressive work! I am trying to reproduce the results from your paper.
When i run eval3d.py i get the following error:

Traceback (most recent call last):
  File "C:/Users/Ramya/PycharmProjects/OSR/ODopenmax/OD/eval3d.py", line 109, in <module>
    BT.propose_H(d1_train)
  File "C:\Users\Ramya\PycharmProjects\OSR\ODopenmax\OD\methods\base_threshold.py", line 113, in propose_H
    trainer.run_epoch(0, phase='all')
  File "C:\Users\Ramya\PycharmProjects\OSR\ODopenmax\OD\utils\iterative_trainer.py", line 125, in run_epoch
    if criterion.size_average:
  File "C:\Users\Ramya\Anaconda3\envs\osr\lib\site-packages\torch\nn\modules\module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'NLLLoss' object has no attribute 'size_average'

Any help would be appreciated. Thank you!

**Comment by ashafaei** [comment]
Hello @RamyaRaghuraman ,
Thank you for taking an interest in this project.

This error is much likely due to the different version of PyTorch that you're using. The attribute `size_average`, which says whether the output of a loss function is averaged over the batch or not, was removed sometime before version 1. PyTorch is using a different mechanism now.

What I would recommend is to create a virtual environment with the right version of PyTorch to make sure nothing breaks.

But If you want a quick fix to this problem, go here [base_threshold.py:L65](https://github.com/ashafaei/OD-test/blob/1808bcdc566c62428fefb8decfca8b556439b60f/methods/base_threshold.py#L65) and after the criterion definition, manually add the following line:
```python
criterion.size_average = True
```
Which sets the missing attribute to its default setting. You may encounter the same error on other methods, which can be manually fixed the same way.

Note that I haven't tested the code with a later version of PyTorch. Keep that in mind.

**Comment by RamyaRaghuraman** [comment]
Thank you @ashafaei for the quick fix! Works fine now. I am also using pytorch version 0.4.0 and visdom version 0.1.8.3.

I still get the following when i run eval3d.py

`Traceback (most recent call last):
  File "C:/Users/RAR7ABT/pj-val-ml/pjval_ml/OSR/OD_test/eval3d.py", line 198, in <module>
    test_acc = BT.test_H(test_mixture)
  File "C:\Users\RAR7ABT\pj-val-ml\pjval_ml\OSR\OD_test\methods\base_threshold.py", line 305, in test_H
    visdom.images(s1.cpu().numpy(), win='in_images')
AttributeError: module 'visdom' has no attribute 'images'`


Also the contents of my launch_visdom.sh after activating the environment is:
`python -m visdom.server -port 8097 -env_path C:\Users\RAR7ABT\pj-val-ml\pjval_ml\OSR\OD_test\workspace\visdom`

**Comment by ashafaei** [comment]
@RamyaRaghuraman The part of the code that generates this error is originally commented out and kept for reference. [base_threshold.py#L290-L298](https://github.com/ashafaei/OD-test/blob/1808bcdc566c62428fefb8decfca8b556439b60f/methods/base_threshold.py#L290-L298). I assume that you'd been trying to execute the commented part.

You'll need to create a Visdom environment since that part of the code does not have an active Visdom session.
Do this
```python
from visdom import Visdom
visdom = Visdom(ipv6=False, env='test')
```
just before getting into the for-loop.
